name: "Build project"

on:
  push:
  # Allow manual dispatch
  workflow_dispatch:

jobs:
  build-phase:
    runs-on: ubuntu-latest
    steps:
      - name: Build App
        run: |
          echo "Starting up"
          echo "Building building building ..."
          sleep 10
          echo "Build success"

      - name: Publish to GCR
        run: |
          echo "Pushing image"
          sleep 5
          echo "Wrapping up"
