name: "Pull and run tests"

on:
  workflow_run:
    workflows: ["Build project"]
    types: [completed]
  # Allow manual dispatch
  workflow_dispatch:

jobs:
  build-phase:
    runs-on: ubuntu-latest
    steps:
      - name: Test App
        run: |
          echo "Pulling app from GCR"
          echo "Testing testing testing..."
          echo "Build success"
